### ISSUE TITLE
main branch's basic-sample doesn't build on Kubuntu 22.04,23.10

### ISSUE THREAD

**Issue by akarnil** [avnet-iotconnect/iotc-generic-c-sdk#47]
Followed the Linux.md guide on building the basic sample.

relevant console log:
```
[ 98%] Built target iotc-c-generic-sdk
[100%] Building C object CMakeFiles/basic-sample.dir/main.c.o
[100%] Linking C executable basic-sample
/usr/bin/ld: warning: libssl.so.3, needed by /usr/lib/x86_64-linux-gnu/libcurl.so, may conflict with libssl.so.1.0.0
/usr/bin/ld: SdkSources/azure-iot-sdk-c/c-utility/libaziotsharedutil.a(tlsio_openssl.c.o): undefined reference to symbol 'OPENSSL_init_ssl@@OPENSSL_3.0.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libssl.so.3: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
gmake[3]: *** [CMakeFiles/basic-sample.dir/build.make:117: basic-sample] Error 1
gmake[2]: *** [CMakeFiles/Makefile2:475: CMakeFiles/basic-sample.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:482: CMakeFiles/basic-sample.dir/rule] Error 2
gmake: *** [Makefile:169: basic-sample] Error 2
```

**Comment by akarnil** [comment]
can confirm doesn't build on 22.04 LTS either

**Comment by nik-markovic** [comment]
I suspect that there's a conflict between libssl's required version of openssl and require version openssl needed for paho.
We should investigate and see how we are linking libcurl and if we can depend on libcurl specific version.

**Comment by nik-markovic** [comment]
Closing due to inactivity.

**Comment by nik-markovic** [comment]
Closing due to inactivity.
